---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - geass.geass.dev
  resources:
  - geassapps
  - geasscaches
  - geasscloudconnections
  - geassclusters
  - geassdatabases
  - geasshareadinesses
  - geasslogicaldatabases
  - geassnodes
  - geassobjectstores
  - geassplatformconfigs
  - geassprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - geass.geass.dev
  resources:
  - geassapps/finalizers
  - geasscaches/finalizers
  - geassclusters/finalizers
  - geassdatabases/finalizers
  - geassnodes/finalizers
  - geassobjectstores/finalizers
  - geassprojects/finalizers
  verbs:
  - update
- apiGroups:
  - geass.geass.dev
  resources:
  - geassapps/status
  - geasscaches/status
  - geasscloudconnections/status
  - geassclusters/status
  - geassdatabases/status
  - geasshareadinesses/status
  - geasslogicaldatabases/status
  - geassnodes/status
  - geassobjectstores/status
  - geassplatformconfigs/status
  - geassprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.cattle.io
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
