apiVersion: geass.geass.dev/v1alpha1
kind: GeassCluster
metadata:
  name: default
  namespace: geass-system
spec:
  version: v1
  serverURL: https://127.0.0.1:6443
  tokenSecretRef:
    name: geass-token
    namespace: geass-system
